image:
  repository: bitnami/kafka
  tag: 3.3.1
deleteTopicEnable: true
heapOpts: -Xmx1024m
deleteTopicEnable: true
autoCreateTopicsEnable: true
replicaCount: 3
resources:
  requests:
    memory: "1Gi"
    cpu: "1"
  limits:
    memory: "2Gi"
    cpu: "2"

externalAccess:
  enabled: true
  autoDiscovery:
    enabled: true
  service:
    type: NodePort
    ports:
      external: 9094

persistence:
  enabled: true
  storageClass: openebs-lvmpv
  size: 10Gi
  mountPath: /bitnami/kafka
serviceAccount:
  create: true
rbac:
  create: true

metrics:
  kafka:
    enabled: true
    image:
      repository: bitnami/kafka-exporter
      tag: 1.6.0-debian-11-r25
    service:
      ports:
        metrics: 9308
      clusterIP: ""
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"

zookeeper:
  enabled: true
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: openebs-lvmpv
    size: 10Gi