version: "3.8"
services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: always
    ports:
      - 6443:6443
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
       
